[theme]
base = "dark"
primaryColor = "#13d47a"
backgroundColor = "#0a1020"
secondaryBackgroundColor = "#11192d"
textColor = "#edf3ff"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
